### ISSUE TITLE
Remove ties from model geometry

### ISSUE THREAD

**Issue by Montandalar** [SamMatzko/minetest_tieless_tracks#1]
Currently the mod basically acts as a copy of advtrains_train_track with the same models but a texture to hide the ties (sleepers). It would be good to reduce overheads by removing the ties from the models entirely.

The source assets live in (advtrains modpack git path:) advtrains/assets/blender/gleis/rail_redo_bk_curves.blend (also rail_crossings.blend, rail_moreturnouts.blend). You can import these objects into your own blend file, delete the ties out of them, save that blend file to your project file, and re-export new obj/b3d files for your mod to use.

It's not possible to change the train's height from the ground currently, so it would be unwise to lower the rails down to ground level unfortunately, as much as that would look nicer.

**Comment by SamMatzko** [comment]
Alrighty, I've removed the crossties from all the track models!
